version: "3"
services:
  db:
    image: mongo:latest
    volumes:
      - ./mongo-configs/init_db.js:/docker-entrypoint-initdb.d/init_db.js
      - /tmp/eesti-database:/data/db
    environment:
      - MONGO_INITDB_DATABASE=words
    expose:
      - 27017
    networks:
      eesti-internal:
        aliases:
          - database

  eesti-backend:
    build: 
      context: ./eesti-helper
      dockerfile: Dockerfile
    image: eesti-backend:${BACKEND_TAG}
    environment:
      - MONGO_HOST=database
      - MONGO_PORT=27017
    ports:
      - 8081:3000
    networks:
      - eesti-internal
      - eesti-external

  eesti-frontend:
    build: 
      context: ./eesti-site
      dockerfile: Dockerfile
    image: eesti-frontend:${FRONTEND_TAG}
    ports:
      - 8080:80
    networks:
      - eesti-external

networks:
  eesti-external:
  eesti-internal:


